/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#0e1320",
        surface: "#0e1320",
        "surface-dim": "#0e1320",
        "surface-bright": "#343947",
        "surface-container-lowest": "#090e1b",
        "surface-container-low": "#161b28",
        "surface-container": "#1a1f2d",
        "surface-container-high": "#252a37",
        "surface-container-highest": "#2f3443",
        "on-surface": "#dee2f5",
        "on-surface-variant": "#c2c6d6",
        "inverse-surface": "#dee2f5",
        "inverse-on-surface": "#2b303e",
        outline: "#8c909f",
        "outline-variant": "#424753",
        "surface-tint": "#afc6ff",
        primary: "#afc6ff",
        "on-primary": "#002d6c",
        "primary-container": "#528dff",
        "on-primary-container": "#00275f",
        "inverse-primary": "#0059c6",
        secondary: "#c3c6d3",
        "on-secondary": "#2c303a",
        "secondary-container": "#454953",
        "on-secondary-container": "#b5b8c4",
        tertiary: "#ffb77b",
        "on-tertiary": "#4d2700",
        "tertiary-container": "#d87802",
        "on-tertiary-container": "#432100",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d9e2ff",
        "primary-fixed-dim": "#afc6ff",
        "on-primary-fixed": "#001a43",
        "on-primary-fixed-variant": "#004398",
        "secondary-fixed": "#dfe2ef",
        "secondary-fixed-dim": "#c3c6d3",
        "on-secondary-fixed": "#181c25",
        "on-secondary-fixed-variant": "#434751",
        "tertiary-fixed": "#ffdcc2",
        "tertiary-fixed-dim": "#ffb77b",
        "on-tertiary-fixed": "#2e1500",
        "on-tertiary-fixed-variant": "#6d3a00",
        "surface-variant": "#2f3443",
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "code-label": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "code-label": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      spacing: {
        "border-width-thick": "2px",
        "border-width-thin": "1px",
        "margin-mobile": "16px",
        "margin-desktop": "24px",
        gutter: "16px",
        unit: "4px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      animation: {
        shimmer: "shimmer 2s infinite linear",
        blink: "blink 1s infinite",
        "progress-stripes": "progress-stripes 1s linear infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "progress-stripes": {
          from: { backgroundPosition: "1rem 0" },
          to: { backgroundPosition: "0 0" },
        },
      },
    },
  },
  plugins: [],
};
