# Generated by Django 4.2.16 on 2026-07-13 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=20)),
                ('pipeline', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'critical'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('info', 'info')], max_length=10)),
                ('severity_score', models.IntegerField(default=0)),
                ('rule_id', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('file', models.TextField(blank=True, null=True)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-severity_score', 'tool'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline', models.CharField(choices=[('static', 'static'), ('dynamic', 'dynamic')], max_length=10)),
                ('target', models.TextField()),
                ('ref', models.CharField(blank=True, default='HEAD', max_length=200)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('complete', 'complete'), ('partial', 'partial'), ('failed', 'failed')], default='queued', max_length=12)),
                ('tools_requested', models.JSONField(default=list)),
                ('tools_done', models.JSONField(default=list)),
                ('tools_failed', models.JSONField(default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('real', 'real'), ('false_positive', 'false_positive'), ('noise', 'noise'), ('error', 'error'), ('pending', 'pending')], default='pending', max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True, default='')),
                ('citation', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='sentriq.finding')),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='sentriq.finding')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='sentriq.scan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HitlAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'approve'), ('deny', 'deny'), ('edit', 'edit')], max_length=10)),
                ('actor', models.CharField(default='anonymous', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('edited_diff', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitl_actions', to='sentriq.finding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diff', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('proposed', 'proposed'), ('approved', 'approved'), ('denied', 'denied'), ('edited', 'edited')], default='proposed', max_length=10)),
                ('model', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixes', to='sentriq.finding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='sentriq.scan'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['scan', 'severity_score'], name='sentriq_fin_scan_id_1969b2_idx'),
        ),
    ]
