# Generated by Django 4.2.16 on 2026-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentriq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixsuggestion',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fixsuggestion',
            name='pr_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fixsuggestion',
            name='pr_status',
            field=models.CharField(choices=[('none', 'none'), ('creating', 'creating'), ('open', 'open'), ('failed', 'failed')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='fixsuggestion',
            name='pr_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
