# Generated by Django 5.2.16 on 2026-07-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentriq', '0002_fixsuggestion_branch_fixsuggestion_pr_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='auto_fix_severity',
            field=models.CharField(blank=True, default='high', max_length=10),
        ),
        migrations.AddField(
            model_name='scan',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scan',
            name='selected_tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(blank=True, default='', max_length=32)),
                ('github_login', models.CharField(blank=True, default='', max_length=120)),
                ('github_access_token', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentriq_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
