# Generated by Django 5.2.16 on 2026-07-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentriq', '0003_scan_auto_fix_severity_scan_requested_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='auto_fix_severity',
            field=models.CharField(blank=True, default='none', max_length=10),
        ),
    ]
