# Generated by Django 5.2.16 on 2026-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentriq', '0004_alter_scan_auto_fix_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='triage_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='triage_total',
            field=models.IntegerField(default=0),
        ),
    ]
