# Generated by Django 5.2.16 on 2026-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentriq', '0005_scan_triage_done_scan_triage_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixsuggestion',
            name='context_strategy',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fixsuggestion',
            name='status',
            field=models.CharField(choices=[('proposed', 'proposed'), ('approved', 'approved'), ('denied', 'denied'), ('edited', 'edited'), ('failed', 'failed')], default='proposed', max_length=10),
        ),
    ]
